XPos/XPos.Web/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataModel;
using XPos.Repository;

namespace XPos.Web.Controllers
{
    public class UploadFileController : Controller
    {
        // GET: UploadFile
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        public ActionResult List(int page = 1, int perPage = 8, string filter = "", string orderBy = "createdate", bool sortAsc = true)
        {
            Pagination pg = UploadFileRepo.Paging(page, perPage, filter, orderBy, sortAsc);
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file, FileCollection model)
        {
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    string[] fileName = file.FileName.Split('.');
                    string newFileName = DateTime.Now.ToString("yyyyMMddHHmmss") + "." + fileName[fileName.Length - 1];
                    string path = Path.Combine(Server.MapPath("~/UploadFiles"), Path.GetFileName(newFileName));
                    file.SaveAs(path);
                    model.FileName = newFileName;
                    ResponseResult result = UploadFileRepo.Update(model);

                    return Json(new
                    {
                        success = result.Success,
                        message = result.Message,
                        entity = result.Entity
                    }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(new
                    {
                        success = false,
                        message = ex.Message
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = "You have no specified a file"
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

XPos/XPos.Web/Views/UploadFile/Index.cshtml
@{
    ViewBag.Title = "File";
}

<h2>@ViewBag.Title Galery</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <input type="button" class="btn btn-success col-sm-1" id="btn-create" value="Create New" />
            <div class="col-sm-2">
                <div class="btn-group">
                    <input type="button" class="btn btn-warning" id="btn-prev" value="< Prev" />
                    <input type="button" class="btn btn-warning" id="btn-next" value="Next >" />
                </div>
            </div>
            <div class="col-sm-3">
                <div class="input-group">
                    <input type="text" class="form-control text-box single-line" id="txt-filter" />
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="btn-filter" type="button">Filter</button>
                    </span>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="input-group">
                    <span class="input-group-addon">Item:</span>
                    <select id="per-page" name="per-page" class="form-control btn btn-default" style="width:75px">
                        <option value="4">4</option>
                        <option value="8" selected>8</option>
                        <option value="16">16</option>
                        <option value="32">32</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="input-group">
                    <span class="input-group-addon">Order By:</span>
                    <select id="order-by" name="order-by" class="form-control btn btn-default" style="width:75px">
                        <option value="createdate">CreateDate</option>
                        <option value="title">Title</option>
                        <option value="filename">File Name</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="input-group">
                    <span class="input-group-addon">Sort:</span>
                    <select id="sorting" name="sorting" class="form-control btn btn-default" style="width:75px">
                        <option value="false">Des</option>
                        <option value="true">Asc</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        Loading...
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        var currPage = 1;
        var maxPage = 1;
        var perPage = 8;
        var filter = "";
        var orderBy = "";
        var sortAsc = true;
        $(document).ready(function () {
            GetList()
        })

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "UploadFile")',
                type: 'get',
                data: { page: currPage, perPage: perPage, filter: filter, orderBy: orderBy, sortAsc: sortAsc },
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        $("#btn-create").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "UploadFile")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        })

        $("#btn-prev").click(function () {
            if (currPage > 1) {
                currPage--;
            }
            GetList(currPage, perPage);
        });
        
        $("#btn-next").click(function () {
            if (currPage < maxPage) {
                currPage++;
            }
            GetList(currPage, perPage);
        });

        $("#per-page").change(function () {
            perPage = $(this).val();
            GetList();
        })

        $("#btn-filter").click(function () {
            filter = $("#txt-filter").val();
            GetList();
        })

        $("#order-by").change(function () {
            orderBy = $(this).val();
            GetList();
        })

        $("#sorting").change(function () {
            sortAsc = $(this).val();
            console.log(sortAsc);
            GetList();
        })

    </script>
}

XPos/XPos.Web/Views/UploadFile/Index2.cshtml
@{
    ViewBag.Title = "Upload File";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "UploadFile", FormMethod.Post, new { id = "form-create", name = "form-create", enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label for="selectedfile" class="control-label col-md-2">Upload File</label>
        <div class="col-md-10">
            <input type="file" name="selectedfile" id="selectedfile" class="btn btn-default" onchange="showPreview(this)"/>
            <br />
            <img src="" alt="No Image" id="img-preview" width="200px" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Upload File" id="upload-file" class="btn btn-success" />
        </div>
    </div>
}

@section Scripts{
    <script type="text/javascript">
        $("#upload-file").click(function () {
            var formData = new FormData();

            formData.append("file", $('#selectedfile')[0].files[0]);

            $.ajax({
                url: '@Url.Action("Create", "UploadFile")',
                type: 'post',
                data: formData,
                contentType: false,
                processData: false,
                success: function (result) {
                    if (result.success) {
                        alert("Success");
                    }
                }
            })
            return false;
        })

        function showPreview(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#img-preview").attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

XPos/XPos.Web/Views/UploadFile/_Create.cshtml
@model XPos.DataModel.FileCollection


@using (Html.BeginForm("Create", "UploadFile", FormMethod.Post, new { id = "form-create", name = "form-create", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="selectedfile" id="selectedfile" class="btn btn-default" onchange="showPreview(this)" />
                <br />
                <img src="~/UploadFiles/no-image.png" alt="No Image" id="img-preview" width="200px" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-default" />
                <input type="button" value="Upload File" id="upload-file" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#upload-file").click(function () {
        var formData = new FormData();

        formData.append("file", $('#selectedfile')[0].files[0]);

        var other_data = $("#form-create").serializeArray();

        $.each(other_data, function (key, input) {
            formData.append(input.name, input.value);
        });

        $.ajax({
            url: '@Url.Action("Create", "UploadFile")',
            type: 'post',
            data: formData,
            contentType: false,
            processData: false,
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    alert(`Save successful\nTitle: ${ent.Title}, File Name: ${ent.FileName}`);
                    $("#modal1").modal("hide");
                    GetList();
                } else {
                    alert(`Error: ${result.message}`);
                }
            }
        })
        return false;
    })

    function showPreview(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#img-preview").attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

XPos/XPos.Web/Views/UploadFile/_List.cshtml
@model IEnumerable<XPos.DataModel.FileCollection>
@{
    int colCnt = 4;
}
@*Page count : @ViewBag.PageCount*@
@foreach (var item in Model)
{
    if (colCnt == 4)
    {
        colCnt = 0;
        @:<div class="row">
    }
              <div class="col-xs-3">
                  Title: @Html.DisplayFor(modelItem => item.Title)<br />
                  File: @Html.DisplayFor(modelItem => item.FileName)<br />
                  <img src="/UploadFiles/@item.FileName" alt="Sample Image" width="100" />
                  <div class="form-group">
                      @Html.LabelFor(modelItem => item.Active)
                      @Html.DisplayFor(modelItem => item.Active)
                  </div>
                  <div class="form-group">
                      @Html.LabelFor(modelItem => item.CreateDate)
                      @Html.DisplayFor(modelItem => item.CreateDate)
                  </div>
              </div>
    if (colCnt == 3)
    {
        @: </div>
    }
    colCnt++;
}


<script type="text/javascript">
    $(document).ready(function () {
        maxPage = @ViewBag.PageCount;
    })
</script>