XPos/XPos.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataModel;
using XPos.Repository;

namespace XPos.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<Product> list = ProductRepo.All();
            return PartialView("_List", list);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Initial");
            ViewBag.VariantList = new SelectList(VariantRepo.ByCategory(-1), "Id", "Initial");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(Product model)
        {
            ResponseResult result = ProductRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(long id)
        {
            Product model = ProductRepo.ById(id);
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Initial");
            ViewBag.VariantList = new SelectList(VariantRepo.ByCategory(model.Variant.CategoryId), "Id", "Initial");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(Product model)
        {
            ResponseResult result = ProductRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

XPos/XPos.Web/Controllers/VariantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataModel;
using XPos.Repository;

namespace XPos.Web.Controllers
{
    public class VariantController : Controller
    {
        // GET: Variant
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<Variant> list = VariantRepo.All();
            return PartialView("_List", list);
        }

        //Get
        public ActionResult Create()
        {
            //Parent List ==> Category
            ViewBag.ParentList = new SelectList(CategoryRepo.All(), "Id", "Name");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(Variant model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult ByCategory(long id = 0)
        {
            // id => Category Id
            List<Variant> list = VariantRepo.ByCategory(id);
            return PartialView("_ByCategory", list);
        }
    }
}

XPos/XPos.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Product";
}

<h2>List of @ViewBag.Title</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <input type="button" class="btn btn-success" id="btn-create" value="Create New" />
        </h3>
    </div>
    <div class="panel-body">
        Loading...
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList()
        })

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "Product")',
                type: 'get',
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        $("#btn-create").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Product")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                }
            });
        })

        function GetById(id) {
            $.ajax({
                url: '@Url.Action("Edit", "Product")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                }
            });
        }

        function DeleteById(id) {
            $.ajax({
                url: '@Url.Action("Delete", "Product")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                }
            });
        }
    </script>
}

XPos/XPos.Web/Views/Product/_Create.cshtml
@model XPos.DataModel.Product


@using (Html.BeginForm("Create","Product", FormMethod.Post, new { id="form-create", name="form-create"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Variant.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Variant.CategoryId, (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Variant.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VariantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VariantId, (IEnumerable<SelectListItem>)ViewBag.VariantList, "Select Variant", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VariantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#Variant_CategoryId").change(function () {
        //console.log($(this).val());
        var catId = $(this).val() == '' ? '-1' : $(this).val();
        $.ajax({
            url: '@Url.Action("ByCategory", "Variant")',
            type: 'get',
            data: { id: catId },
            success: function (result) {
                $("#VariantId").html(result);
            }
        })
    })

    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    alert(`Save successful\nInitial: ${ent.Initial}, Name: ${ent.Name}`);
                    $("#modal1").modal("hide");
                    GetList()
                } else {
                    alert(`Error: ${result.message}`);
                }
            }
        })
        return false;
    })
</script>

XPos/XPos.Web/Views/Product/_Edit.cshtml
@model XPos.DataModel.Product


@using (Html.BeginForm("Edit","Product", FormMethod.Post, new { id="form-edit", name="form-edit"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Variant.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Variant.CategoryId, (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Variant.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VariantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VariantId, (IEnumerable<SelectListItem>)ViewBag.VariantList, "Select Variant", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VariantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
      $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    alert(`Save successful\nInitial: ${ent.Initial}, Name: ${ent.Name}`);
                    $("#modal1").modal("hide");
                    GetList()
                } else {
                    alert(`Error: ${result.message}`);
                }
            }
        })
        return false;
    })

</script>

XPos/XPos.Web/Views/Product/_List.cshtml
@model IEnumerable<XPos.DataModel.Product>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Variant.Initial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Initial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Variant.Initial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Initial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            <div class="btn-group btn-group-sm">
                <button type="button" class="btn btn-warning btn-edit" data-id="@item.Id" title="Edit" onclick="GetById(@item.Id)">Edit</button>
                <button type="button" class="btn btn-danger btn-delete" data-id="@item.Id" onclick="DeleteById(@item.Id)" title="Delete">Delete</button>
            </div>
        </td>
    </tr>
}

</table>